lib/pi_wallet/web/router.ex
defmodule PiWallet.Web.Router do
  use PiWallet.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # plug BasicAuth, use_config: {:pi_wallet, :basic_auth}
    plug BasicAuth, callback: &PiWallet.BasicAuthCallback.check_credentials/3
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PiWallet.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index, as: :dashboard
    get "/transactions", TransactionController, :index
    get "/side_stakes", StakeController, :index
    get "/settings", SettingController, :index
    scope "/commands/" do
      post "/lock", CommandController, :lock
      post "/unlock", CommandController, :unlock
      post "/upgrade_interface", CommandController, :upgrade_interface
      post "/upgrade_daemon", CommandController, :upgrade_daemon
      post "/update_wifi_settings", CommandController, :update_wifi_settings
      post "/upload_wallet", CommandController, :upload_wallet
      get "/download_wallet", CommandController, :download_wallet
      post "/create_transaction", CommandController, :create_transaction
      post "/set_wallet_passphrase", CommandController, :set_wallet_passphrase
      post "/clear_transactions", CommandController, :clear_transactions
      post "/scan_for_transactions", CommandController, :scan_for_transactions
      post "/side_stakes", CommandController, :add_side_stake
      # delete "/side_stakes/:address", CommandController, :remove_side_stake
      # Should be using delete
      get "/side_stakes/:address", CommandController, :remove_side_stake
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", PiWallet.Web.Api do
    pipe_through :api

    get "/wifi_networks", NetworkController, :index
    get "/transactions", TransactionController, :index
    get "/side_stakes", StakeController, :index
    get "/info", InfoController, :index
  end
end

lib/pi_wallet/web/controllers/setting_controller.ex
defmodule PiWallet.Web.SettingController do
  use PiWallet.Web, :controller
  alias PiWallet.WifiConfig
  alias PiWallet.WalletClient

  def index(conn, _params) do
    render conn, "index.html", wifi_config: WifiConfig.read(), wallet_encrypted: wallet_is_encrypted()
  end

  defp wallet_is_encrypted() do
    case WalletClient.wallet_info() do
      {:ok, %{"unlocked_until" => _}} ->
        true
      _ ->
        false
    end
  end
end

lib/pi_wallet/web/views/setting_view.ex
defmodule PiWallet.Web.SettingView do
  use PiWallet.Web, :view
end

lib/pi_wallet/web/templates/setting/index.html.eex
<div class="jumbotron">
  <ul class="nav nav-tabs nav-justified">
    <li role="presentation" class="active"><a data-toggle="tab" href="#wifi">WiFi</a></li>
    <li role="presentation"><a data-toggle="tab" href="#wallet">Wallet</a></li>
    <%# <li role="presentation"><a data-toggle="tab" href="#firmware">Firmware</a></li> %>
  </ul>
  <div class="tab-content">
    <div id="wifi" class="tab-pane fade in active">
      <h4>WiFi</h4>
      <%= form_for @conn, command_path(@conn, :update_wifi_settings), [as: :command, class: "form", onSubmit: "return confirm('Please note that your device will restart after configuring the network')"], fn f -> %>
        <div class="form-group">
          <label>SSID</label>
          <div class="input-group">
            <select class="form-control" disabled="disabled" id="ssid_list">
              <option value="">----</option>
            </select>
            <span class="input-group-btn">
              <button id="ssid_list_refresh" class="btn btn-default">Refresh</button>
            </span>
          </div>
          <small>or enter the Network SSID manually</small>
          <%= text_input f, :ssid, class: "form-control", value: @wifi_config["ssid"] %>
          <label>Encryption</label>
          <select class="form-control" disabled="disabled">
            <option>WPA2 Personal (currently the only supported option)</option>
          </select>
          <label>Passphrase</label>
          <%= text_input f, :passphrase, class: "form-control", value: @wifi_config["psk"] %>
        </div>
        <div class="form-group">
          <%= submit "Save", class: "btn btn-primary form-control" %>
        </div>
      <% end %>
    </div>
    <div id="wallet" class="tab-pane fade">
      <h4>Upload new wallet</h4>
      <%= form_for @conn, command_path(@conn, :upload_wallet), [as: :command, class: "form", multipart: true, onSubmit: "return confirm('Please beware, this will overwrite the current wallet file on the server. This operation is NOT reversible.')"], fn f -> %>
        <div class="form-group">
          <label>Wallet</label>
          <%= file_input f, :file, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit "Upload", class: "btn btn-primary form-control" %>
        </div>
        <small>If you don't see the correct balance after uploading a new wallet, click 'Clear transactions' followed by 'Scan for transactions'. The scan operation can take several minutes so please be patient.</small>
      <% end %>
      <hr>
      <h4>Download Wallet</h4>
      <%= link "Download", to: command_path(@conn, :download_wallet), class: "btn btn-primary form-control" %>
      <hr>
      <%= if @wallet_encrypted do %>
        <h4>Change Wallet Passphrase</h4>
      <% else %>
        <h4>Encrypt Wallet</h4>
      <% end %>
      <%= form_for @conn, command_path(@conn, :set_wallet_passphrase), [as: :command, class: "form", onSubmit: "return confirm('Please beware, should you loose the passphrase you will not be able to access the funds in this wallet and there is no way of recovering them without a previous backup of the wallet file. This operation is NOT reversible.')"], fn f -> %>
        <%= if @wallet_encrypted do %>
          <div class="form-group">
            <label>Current Password</label>
            <%= password_input f, :current_passphrase, class: "form-control" %>
          </div>
        <% end %>
        <div class="form-group">
          <label>New Password</label>
          <%= password_input f, :new_passphrase, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>New Password Confirmation</label>
          <%= password_input f, :new_passphrase_confirmation, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit "Encrypt", class: "btn btn-primary form-control" %>
        </div>
        <small>Encrypting the wallet will prevent access to it for a short while, please be patient.</small>
      <% end %>
      <hr>
      <h4>Other Operations</h4>
      <%= form_for @conn, command_path(@conn, :clear_transactions), [as: :command, class: "form", onSubmit: "return confirm('After clearing the transactions you\'ll normally need to run \'Scan for transactions\' afterwards.')"], fn _ -> %>
        <div class="form-group">
          <%= submit "Clear transactions", class: "btn btn-primary form-control" %>
        </div>
      <% end %>
      <%= form_for @conn, command_path(@conn, :scan_for_transactions), [as: :command, class: "form", onSubmit: "return confirm('This operation can take several minutes so please be patient.')"], fn _ -> %>
        <div class="form-group">
          <%= submit "Scan for transactions", class: "btn btn-primary form-control" %>
        </div>
        <small>The interface might become unresponsive while the transaction scanning is in progress.</small>
      <% end %>
    </div>
    <div id="firmware" class="tab-pane fade">
      <h4>Upload new interface</h4>
      <%= form_for @conn, command_path(@conn, :upgrade_interface), [as: :command, class: "form", multipart: true], fn f -> %>
        <div class="form-group">
          <label>Interface Binary</label>
          <%= file_input f, :file, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit "Upload", class: "btn btn-primary form-control" %>
        </div>
      <% end %>

      <h4>Upload new daemon</h4>
      <%= form_for @conn, command_path(@conn, :upgrade_daemon), [as: :command, class: "form", multipart: true], fn f -> %>
        <div class="form-group">
          <label>Interface Daemon</label>
          <%= file_input f, :file, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= submit "Upload", class: "btn btn-primary form-control" %>
        </div>
      <% end %>
    </div>
  </div>
</div>