lib/pi_wallet/web/router.ex
defmodule PiWallet.Web.Router do
  use PiWallet.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # plug BasicAuth, use_config: {:pi_wallet, :basic_auth}
    plug BasicAuth, callback: &PiWallet.BasicAuthCallback.check_credentials/3
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PiWallet.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index, as: :dashboard
    get "/transactions", TransactionController, :index
    get "/side_stakes", StakeController, :index
    get "/settings", SettingController, :index
    scope "/commands/" do
      post "/lock", CommandController, :lock
      post "/unlock", CommandController, :unlock
      post "/upgrade_interface", CommandController, :upgrade_interface
      post "/upgrade_daemon", CommandController, :upgrade_daemon
      post "/update_wifi_settings", CommandController, :update_wifi_settings
      post "/upload_wallet", CommandController, :upload_wallet
      get "/download_wallet", CommandController, :download_wallet
      post "/create_transaction", CommandController, :create_transaction
      post "/set_wallet_passphrase", CommandController, :set_wallet_passphrase
      post "/clear_transactions", CommandController, :clear_transactions
      post "/scan_for_transactions", CommandController, :scan_for_transactions
      post "/side_stakes", CommandController, :add_side_stake
      # delete "/side_stakes/:address", CommandController, :remove_side_stake
      # Should be using delete
      get "/side_stakes/:address", CommandController, :remove_side_stake
    end
  end

  # Other scopes may use custom stacks.
  scope "/api", PiWallet.Web.Api do
    pipe_through :api

    get "/wifi_networks", NetworkController, :index
    get "/transactions", TransactionController, :index
    get "/side_stakes", StakeController, :index
    get "/info", InfoController, :index
  end
end

lib/pi_wallet/web/views/layout_view.ex
defmodule PiWallet.Web.LayoutView do
  use PiWallet.Web, :view

  def render_shared(template, assigns \\ []) do
    render(PiWallet.Web.LayoutView, template, assigns)
  end
end

lib/pi_wallet/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>PinkPi</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="author" content="DownSouth">
    <meta name="description" content="The PinkPi Web Interface">
    <meta name="apple-mobile-web-app-title" content="PinkPi">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= static_path(@conn, "/images/web-icon.png") %>">
    <link rel="mask-icon" href="<%= static_path(@conn, "/images/pin-icon.svg") %>" color="#eb78ab">
    <link rel="apple-touch-icon" sizes="540x540" href="<%= static_path(@conn, "/images/mobile-icon.png") %>">
    <link rel="manifest" href="/manifest.json">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="navbar hidden-xs">
          <%= render_shared "nav.html", [conn: @conn] %>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <footer class="visible-xs">
      <div class="container">
        <nav class="navbar">
          <%= render_shared "xs_nav.html", [conn: @conn] %>
        </nav>
      </div>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/pi_wallet/web/templates/layout/nav.html.eex
<ul class="nav nav-pills nav-justified">
  <%= render_shared "nav_link.html", [conn: @conn, path: dashboard_path(@conn, :index), name: raw('<i class="fas fa-chart-line" aria-hidden="true"></i> Dashboard'), tooltip: "Dashboard"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: transaction_path(@conn, :index), name: raw('<i class="fas fa-exchange" aria-hidden="true"></i> Transactions'), tooltip: "Transactions"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: stake_path(@conn, :index), name: raw('<i style="margin-right: 2px;" class="fas fa-code-branch fa-rotate-90" aria-hidden="true"></i> Side Stakes'), tooltip: "Side Stakes"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: setting_path(@conn, :index), name: raw('<i class="fas fa-cog" aria-hidden="true"></i> Settings'), tooltip: "Settings"] %>
</ul>

lib/pi_wallet/web/templates/layout/nav_link.html.eex
<%= if @conn.request_path == @path do %>
  <li role="presentation" class="active"><%= link @name, to: @path, title: @tooltip %></li>
<% else %>
  <li role="presentation"><%= link @name, to: @path, title: @tooltip %></li>
<% end %>

lib/pi_wallet/web/templates/layout/xs_nav.html.eex
<ul class="nav nav-pills nav-justified">
  <%= render_shared "nav_link.html", [conn: @conn, path: dashboard_path(@conn, :index), name: raw('<i class="fas fa-chart-line fa-2x" aria-hidden="true"></i>'), tooltip: "Dashboard"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: transaction_path(@conn, :index), name: raw('<i class="fas fa-exchange fa-2x" aria-hidden="true"></i>'), tooltip: "Transactions"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: stake_path(@conn, :index), name: raw('<i class="fas fa-code-branch fa-rotate-90 fa-2x" aria-hidden="true"></i>'), tooltip: "Side Stakes"] %>
  <%= render_shared "nav_link.html", [conn: @conn, path: setting_path(@conn, :index), name: raw('<i class="fas fa-cog fa-2x" aria-hidden="true"></i>'), tooltip: "Settings"] %>
</ul>